//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM.CommonLibrary.ResourceFile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessageIds {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessageIds() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RM.CommonLibrary.ResourceFile.ErrorMessageIds", typeof(ErrorMessageIds).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following arguments for the method are null {0}.
        /// </summary>
        public static string Err_ArgumentmentNullException {
            get {
                return ResourceManager.GetString("Err_ArgumentmentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data you are trying to modify has been already modified by another user..
        /// </summary>
        public static string Err_Concurrency {
            get {
                return ResourceManager.GetString("Err_Concurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application error occured. Please contact your administrator..
        /// </summary>
        public static string Err_Default {
            get {
                return ResourceManager.GetString("Err_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity trying to search cannot be found..
        /// </summary>
        public static string Err_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Err_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown attempting to execute the error handler..
        /// </summary>
        public static string Err_ExecutingErrorHandler {
            get {
                return ResourceManager.GetString("Err_ExecutingErrorHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underlying provider does not support this operation..
        /// </summary>
        public static string Err_InvalidOperationExceptionForCountAsync {
            get {
                return ResourceManager.GetString("Err_InvalidOperationExceptionForCountAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source does not implement IDbAsyncQueryProvider.
        /// </summary>
        public static string Err_InvalidOperationExceptionForFirstorDefault {
            get {
                return ResourceManager.GetString("Err_InvalidOperationExceptionForFirstorDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are more than one element in sequence for SingleOrDefault() extention.
        /// </summary>
        public static string Err_InvalidOperationExceptionForSingleorDefault {
            get {
                return ResourceManager.GetString("Err_InvalidOperationExceptionForSingleorDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to use unsupported behavior..
        /// </summary>
        public static string Err_NotSupportedException {
            get {
                return ResourceManager.GetString("Err_NotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context or connection have been disposed..
        /// </summary>
        public static string Err_ObjectDisposedException {
            get {
                return ResourceManager.GetString("Err_ObjectDisposedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of elements in source is larger than MaxValue..
        /// </summary>
        public static string Err_OverflowException {
            get {
                return ResourceManager.GetString("Err_OverflowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured on adding new {0}..
        /// </summary>
        public static string Err_SqlAddException {
            get {
                return ResourceManager.GetString("Err_SqlAddException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while deleting {0}..
        /// </summary>
        public static string Err_SqlDeleteException {
            get {
                return ResourceManager.GetString("Err_SqlDeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured on modifying {0}..
        /// </summary>
        public static string Err_SqlUpdateException {
            get {
                return ResourceManager.GetString("Err_SqlUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while generating token.
        /// </summary>
        public static string Err_Token {
            get {
                return ResourceManager.GetString("Err_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled application error occurred and has been logged. Please contact your administrator..
        /// </summary>
        public static string Err_UnHandled {
            get {
                return ResourceManager.GetString("Err_UnHandled", resourceCulture);
            }
        }
    }
}
