//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM.CommonLibrary.ResourceFile
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReferenceDataValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReferenceDataValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RM.CommonLibrary.ResourceFile.ReferenceDataValues", typeof(ReferenceDataValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string AccesLinkMinimumLength {
            get {
                return ResourceManager.GetString("AccesLinkMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40.
        /// </summary>
        internal static string AccessLinkDiffRoadMaxDistance {
            get {
                return ResourceManager.GetString("AccessLinkDiffRoadMaxDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40.
        /// </summary>
        internal static string AccessLinkSameRoadMaxDistance {
            get {
                return ResourceManager.GetString("AccessLinkSameRoadMaxDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Required.
        /// </summary>
        internal static string ActionRequired {
            get {
                return ResourceManager.GetString("ActionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amber.
        /// </summary>
        internal static string Amber {
            get {
                return ResourceManager.GetString("Amber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string ARoad {
            get {
                return ResourceManager.GetString("ARoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string ARoadPrimary {
            get {
                return ResourceManager.GetString("ARoadPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        internal static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        internal static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string BRoad {
            get {
                return ResourceManager.GetString("BRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string BRoadPrimary {
            get {
                return ResourceManager.GetString("BRoadPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.66.
        /// </summary>
        internal static string BusinessPavementWidthMultiplicationFactor {
            get {
                return ResourceManager.GetString("BusinessPavementWidthMultiplicationFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.5.
        /// </summary>
        internal static string BusinessRoadWidthMultiplicationFactor {
            get {
                return ResourceManager.GetString("BusinessRoadWidthMultiplicationFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Unit.
        /// </summary>
        internal static string CollectionUnit {
            get {
                return ResourceManager.GetString("CollectionUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting Link.
        /// </summary>
        internal static string ConnectingLink {
            get {
                return ResourceManager.GetString("ConnectingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting Node.
        /// </summary>
        internal static string ConnectingNode {
            get {
                return ResourceManager.GetString("ConnectingNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        internal static string DeliveryPointOperationalStatus_Live {
            get {
                return ResourceManager.GetString("DeliveryPointOperationalStatus_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Unit.
        /// </summary>
        internal static string DeliveryUnit {
            get {
                return ResourceManager.GetString("DeliveryUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        internal static string DeliveryUnitStatus_Live {
            get {
                return ResourceManager.GetString("DeliveryUnitStatus_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned.
        /// </summary>
        internal static string DeliveryUnitStatus_Planned {
            get {
                return ResourceManager.GetString("DeliveryUnitStatus_Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DP.
        /// </summary>
        internal static string DP {
            get {
                return ResourceManager.GetString("DP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft Pending Approval.
        /// </summary>
        internal static string DraftPendingApproval {
            get {
                return ResourceManager.GetString("DraftPendingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft Pending Review.
        /// </summary>
        internal static string DraftPendingReview {
            get {
                return ResourceManager.GetString("DraftPendingReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        internal static string External {
            get {
                return ResourceManager.GetString("External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Capacity Trolley.
        /// </summary>
        internal static string HighCapacityTrolley {
            get {
                return ResourceManager.GetString("HighCapacityTrolley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informational.
        /// </summary>
        internal static string Informational {
            get {
                return ResourceManager.GetString("Informational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        internal static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        internal static string Live {
            get {
                return ResourceManager.GetString("Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Route.
        /// </summary>
        internal static string LiveRoute {
            get {
                return ResourceManager.GetString("LiveRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string LocalAccessRoad {
            get {
                return ResourceManager.GetString("LocalAccessRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string LocalRoad {
            get {
                return ResourceManager.GetString("LocalRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string MinorRoad {
            get {
                return ResourceManager.GetString("MinorRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string Motorway {
            get {
                return ResourceManager.GetString("Motorway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple.
        /// </summary>
        internal static string Multiple {
            get {
                return ResourceManager.GetString("Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Link.
        /// </summary>
        internal static string NetworkLinkType_PathLink {
            get {
                return ResourceManager.GetString("NetworkLinkType_PathLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Live.
        /// </summary>
        internal static string NotLive {
            get {
                return ResourceManager.GetString("NotLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number in Name.
        /// </summary>
        internal static string NumberinName {
            get {
                return ResourceManager.GetString("NumberinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NYB.
        /// </summary>
        internal static string NYB {
            get {
                return ResourceManager.GetString("NYB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        internal static string Organisation {
            get {
                return ResourceManager.GetString("Organisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        internal static string Out {
            get {
                return ResourceManager.GetString("Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAF.
        /// </summary>
        internal static string PAF {
            get {
                return ResourceManager.GetString("PAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string PathLink {
            get {
                return ResourceManager.GetString("PathLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Node.
        /// </summary>
        internal static string PathNode {
            get {
                return ResourceManager.GetString("PathNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string PavementWidth {
            get {
                return ResourceManager.GetString("PavementWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Delete in FMO.
        /// </summary>
        internal static string PendingDeleteinFMO {
            get {
                return ResourceManager.GetString("PendingDeleteinFMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Delete in PAF.
        /// </summary>
        internal static string PendingDeleteinPAF {
            get {
                return ResourceManager.GetString("PendingDeleteinPAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned.
        /// </summary>
        internal static string Planned {
            get {
                return ResourceManager.GetString("Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Route.
        /// </summary>
        internal static string PlannedRoute {
            get {
                return ResourceManager.GetString("PlannedRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO BOX.
        /// </summary>
        internal static string POBOX {
            get {
                return ResourceManager.GetString("POBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        internal static string PostalAddressStatus_Live {
            get {
                return ResourceManager.GetString("PostalAddressStatus_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string PropertyDepth {
            get {
                return ResourceManager.GetString("PropertyDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residential.
        /// </summary>
        internal static string Residential {
            get {
                return ResourceManager.GetString("Residential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.5.
        /// </summary>
        internal static string ResidentialHouseDepthMultiplicationFactor {
            get {
                return ResourceManager.GetString("ResidentialHouseDepthMultiplicationFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.66.
        /// </summary>
        internal static string ResidentialPavementWidthMultiplicationFactor {
            get {
                return ResourceManager.GetString("ResidentialPavementWidthMultiplicationFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.5.
        /// </summary>
        internal static string ResidentialRoadWidthMultiplicationFactor {
            get {
                return ResourceManager.GetString("ResidentialRoadWidthMultiplicationFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string RestrictedLocalAccessRoad {
            get {
                return ResourceManager.GetString("RestrictedLocalAccessRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string RestrictedSecondaryAccessRoad {
            get {
                return ResourceManager.GetString("RestrictedSecondaryAccessRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMG DP.
        /// </summary>
        internal static string RMGDP {
            get {
                return ResourceManager.GetString("RMGDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMG Node.
        /// </summary>
        internal static string RMGNode {
            get {
                return ResourceManager.GetString("RMGNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string RMGPath {
            get {
                return ResourceManager.GetString("RMGPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string RMGRoad {
            get {
                return ResourceManager.GetString("RMGRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM Van.
        /// </summary>
        internal static string RMVan {
            get {
                return ResourceManager.GetString("RMVan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM Van (Shared).
        /// </summary>
        internal static string RMVanShared {
            get {
                return ResourceManager.GetString("RMVanShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Link.
        /// </summary>
        internal static string RoadLink {
            get {
                return ResourceManager.GetString("RoadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Node.
        /// </summary>
        internal static string RoadNode {
            get {
                return ResourceManager.GetString("RoadNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string SecondaryAccessRoad {
            get {
                return ResourceManager.GetString("SecondaryAccessRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        internal static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub building.
        /// </summary>
        internal static string Subbuilding {
            get {
                return ResourceManager.GetString("Subbuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppressed.
        /// </summary>
        internal static string Suppressed {
            get {
                return ResourceManager.GetString("Suppressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HighCapacityTrolley.
        /// </summary>
        internal static string TransportType_HighCapacityTrolley {
            get {
                return ResourceManager.GetString("TransportType_HighCapacityTrolley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMVan.
        /// </summary>
        internal static string TransportType_RMVan {
            get {
                return ResourceManager.GetString("TransportType_RMVan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMVan(Shared).
        /// </summary>
        internal static string TransportType_RMVanShared {
            get {
                return ResourceManager.GetString("TransportType_RMVanShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        internal static string UI_DeliveryPoint_Type_Single {
            get {
                return ResourceManager.GetString("UI_DeliveryPoint_Type_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string UI_MinNumSearchCharacters {
            get {
                return ResourceManager.GetString("UI_MinNumSearchCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        internal static string UI_RouteLog_Status_Live {
            get {
                return ResourceManager.GetString("UI_RouteLog_Status_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined.
        /// </summary>
        internal static string UserDefined {
            get {
                return ResourceManager.GetString("UserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USR.
        /// </summary>
        internal static string USR {
            get {
                return ResourceManager.GetString("USR", resourceCulture);
            }
        }
    }
}
