//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM.CommonLibrary.ResourceFile
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReferenceDataCategoryNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReferenceDataCategoryNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RM.CommonLibrary.ResourceFile.ReferenceDataCategoryNames", typeof(ReferenceDataCategoryNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Link Direction.
        /// </summary>
        internal static string AccessLinkDirection {
            get {
                return ResourceManager.GetString("AccessLinkDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Link Parameters.
        /// </summary>
        internal static string AccessLinkParameters {
            get {
                return ResourceManager.GetString("AccessLinkParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Link Status.
        /// </summary>
        internal static string AccessLinkStatus {
            get {
                return ResourceManager.GetString("AccessLinkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Link Type.
        /// </summary>
        internal static string AccessLinkType {
            get {
                return ResourceManager.GetString("AccessLinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Provider.
        /// </summary>
        internal static string DataProvider {
            get {
                return ResourceManager.GetString("DataProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Point Operational Status.
        /// </summary>
        internal static string DeliveryPointOperationalStatus {
            get {
                return ResourceManager.GetString("DeliveryPointOperationalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeliveryPoint Use Indicator.
        /// </summary>
        internal static string DeliveryPointUseIndicator {
            get {
                return ResourceManager.GetString("DeliveryPointUseIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Route Method Type.
        /// </summary>
        internal static string DeliveryRouteMethodType {
            get {
                return ResourceManager.GetString("DeliveryRouteMethodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Route Operational Status.
        /// </summary>
        internal static string DeliveryRouteOperationalStatus {
            get {
                return ResourceManager.GetString("DeliveryRouteOperationalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Unit Status.
        /// </summary>
        internal static string DeliveryUnitStatus {
            get {
                return ResourceManager.GetString("DeliveryUnitStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Link Type.
        /// </summary>
        internal static string NetworkLinkType {
            get {
                return ResourceManager.GetString("NetworkLinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Node Type.
        /// </summary>
        internal static string NetworkNodeType {
            get {
                return ResourceManager.GetString("NetworkNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Priority.
        /// </summary>
        internal static string NotificationPriority {
            get {
                return ResourceManager.GetString("NotificationPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Type.
        /// </summary>
        internal static string NotificationType {
            get {
                return ResourceManager.GetString("NotificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Object Type.
        /// </summary>
        internal static string OperationalObjectType {
            get {
                return ResourceManager.GetString("OperationalObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Address Status.
        /// </summary>
        internal static string PostalAddressStatus {
            get {
                return ResourceManager.GetString("PostalAddressStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Address Type.
        /// </summary>
        internal static string PostalAddressType {
            get {
                return ResourceManager.GetString("PostalAddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport Type.
        /// </summary>
        internal static string TransportType {
            get {
                return ResourceManager.GetString("TransportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI_DeliveryPoint_Type.
        /// </summary>
        internal static string UI_DeliveryPoint_Type {
            get {
                return ResourceManager.GetString("UI_DeliveryPoint_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI_RouteLog_Status.
        /// </summary>
        internal static string UI_RouteLog_Status {
            get {
                return ResourceManager.GetString("UI_RouteLog_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI_RouteLogSearch_SelectionType.
        /// </summary>
        internal static string UI_RouteLogSearch_SelectionType {
            get {
                return ResourceManager.GetString("UI_RouteLogSearch_SelectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI_SearchRules.
        /// </summary>
        internal static string UI_SearchRules {
            get {
                return ResourceManager.GetString("UI_SearchRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Location Type.
        /// </summary>
        internal static string UnitLocationType {
            get {
                return ResourceManager.GetString("UnitLocationType", resourceCulture);
            }
        }
    }
}
