//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fmo.Common.ResourceFile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessageIds {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessageIds() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fmo.Common.ResourceFile.ErrorMessageIds", typeof(ErrorMessageIds).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArgumentmentNull.
        /// </summary>
        public static string Err_ArgumentmentNullException {
            get {
                return ResourceManager.GetString("Err_ArgumentmentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrency.
        /// </summary>
        public static string Err_Concurrency {
            get {
                return ResourceManager.GetString("Err_Concurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Err_Default {
            get {
                return ResourceManager.GetString("Err_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityNotFound.
        /// </summary>
        public static string Err_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Err_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecutingErrorHandler.
        /// </summary>
        public static string Err_ExecutingErrorHandler {
            get {
                return ResourceManager.GetString("Err_ExecutingErrorHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidOperationForCountAsync.
        /// </summary>
        public static string Err_InvalidOperationExceptionForCountAsync {
            get {
                return ResourceManager.GetString("Err_InvalidOperationExceptionForCountAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidOperationForFirstorDefault.
        /// </summary>
        public static string Err_InvalidOperationExceptionForFirstorDefault {
            get {
                return ResourceManager.GetString("Err_InvalidOperationExceptionForFirstorDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidOperationForSingleorDefault.
        /// </summary>
        public static string Err_InvalidOperationExceptionForSingleorDefault {
            get {
                return ResourceManager.GetString("Err_InvalidOperationExceptionForSingleorDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotSupported.
        /// </summary>
        public static string Err_NotSupportedException {
            get {
                return ResourceManager.GetString("Err_NotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectDisposed.
        /// </summary>
        public static string Err_ObjectDisposedException {
            get {
                return ResourceManager.GetString("Err_ObjectDisposedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overflow.
        /// </summary>
        public static string Err_OverflowException {
            get {
                return ResourceManager.GetString("Err_OverflowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlAdd.
        /// </summary>
        public static string Err_SqlAddException {
            get {
                return ResourceManager.GetString("Err_SqlAddException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlDelete.
        /// </summary>
        public static string Err_SqlDeleteException {
            get {
                return ResourceManager.GetString("Err_SqlDeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlUpdate.
        /// </summary>
        public static string Err_SqlUpdateException {
            get {
                return ResourceManager.GetString("Err_SqlUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string Err_Token {
            get {
                return ResourceManager.GetString("Err_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnHandled.
        /// </summary>
        public static string Err_UnHandled {
            get {
                return ResourceManager.GetString("Err_UnHandled", resourceCulture);
            }
        }
    }
}
