//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fmo.Common.ResourceFile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FmoMessagesConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FmoMessagesConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fmo.Common.ResourceFile.FmoMessagesConstants", typeof(FmoMessagesConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9002.
        /// </summary>
        public static string EventID {
            get {
                return ResourceManager.GetString("EventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FMO Exception.
        /// </summary>
        public static string EventLogTitle {
            get {
                return ResourceManager.GetString("EventLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Error Occured. Please contact your administrator..
        /// </summary>
        public static string GenralErrorMessage {
            get {
                return ResourceManager.GetString("GenralErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application error occurred and has been logged. Please contact your administrator..
        /// </summary>
        public static string LogAndThrowErrorMessage {
            get {
                return ResourceManager.GetString("LogAndThrowErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string LogCategory {
            get {
                return ResourceManager.GetString("LogCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Logging_LogName {
            get {
                return ResourceManager.GetString("Logging_LogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FMO Logging.
        /// </summary>
        public static string Logging_LogSource {
            get {
                return ResourceManager.GetString("Logging_LogSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp: {timestamp(local)}{newline}Message: {message}{newline}Category: {category}{newline}Priority: {priority}{newline}EventId: {eventid}{newline}Severity: {severity}{newline}Title:{title}{newline}Machine: {localMachine}{newline}App Domain: {localAppDomain}{newline}ProcessId: {localProcessId}{newline}Process Name: {localProcessName}{newline}Thread Name: {threadName}{newline}Win32 ThreadId:{win32ThreadId}{newline}Extended Properties: {dictionary({key} - {value}{newline})}.
        /// </summary>
        public static string Logging_TextFormat {
            get {
                return ResourceManager.GetString("Logging_TextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string LogSource_LogSourceName {
            get {
                return ResourceManager.GetString("LogSource_LogSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExceptionShielding.
        /// </summary>
        public static string Policy_ExceptionShielding {
            get {
                return ResourceManager.GetString("Policy_ExceptionShielding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogAndWrap.
        /// </summary>
        public static string Policy_LogAndWrap {
            get {
                return ResourceManager.GetString("Policy_LogAndWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoggingAndReplacingException.
        /// </summary>
        public static string Policy_LoggingAndReplacingException {
            get {
                return ResourceManager.GetString("Policy_LoggingAndReplacingException", resourceCulture);
            }
        }
    }
}
